### ISSUE TITLE
Request: Append to file

### ISSUE THREAD

**Issue by EHCanadian** [gurikbal/Merge-files-in-one#2]
Say I have 3 files I wish to merge.
Using this with notepad++, It just add the second file data on the same lines.

Ability to append data to the original file with top or bottom
Would need to support windows and unix end line char.

File1 text data:
abc
def

File2 text data:
hij
klm

What it does
abc hij
def klm

**Comment by gurikbal** [comment]
> Say I have 3 files I wish to merge.
> Using this with notepad++, It just add the second file data on the same lines.
> 
> Ability to append data to the original file with top or bottom
> Would need to support windows and unix end line char.
> 
> File1 text data:
> abc
> def
> 
> File2 text data:
> hij
> klm
> 
> What it does
> abc hij
> def klm

download and install plugin you want.
http://www.scout-soft.com/combine/

**Comment by DogancanYr** [comment]
https://web.archive.org/web/20200726080013/http://www.scout-soft.com/combine/combine.dll
